-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 11:31:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projektentomophagie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projektentomophagie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projektentomophagie` DEFAULT CHARACTER SET utf8 ;
USE `projektentomophagie` ;

-- -----------------------------------------------------
-- Table `projektentomophagie`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektentomophagie`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projektentomophagie`.`seriennummer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektentomophagie`.`seriennummer` (
  `idSeriennummer` INT(11) NOT NULL,
  `Seriennummern` INT(11) NOT NULL,
  `SeriennumerAktiviert` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idSeriennummer`),
  INDEX `Seriennummern` (`Seriennummern` ASC),
  INDEX `user_idUser` (`idSeriennummer` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `projektentomophagie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektentomophagie`.`user` (
  `id` INT(11) NOT NULL,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  `Seriennummer_Seriennumern` INT(11) NOT NULL,
  `Seriennummer_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC),
  INDEX `Seriennummer_Seriennumern` (`Seriennummer_Seriennumern` ASC),
  INDEX `Seriennummer_id` (`Seriennummer_id` ASC),
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`Seriennummer_Seriennumern`)
    REFERENCES `projektentomophagie`.`seriennummer` (`Seriennummern`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`Seriennummer_id`)
    REFERENCES `projektentomophagie`.`seriennummer` (`idSeriennummer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projektentomophagie`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projektentomophagie`.`data` (
  `idData` INT NOT NULL,
  `DataTemperatur` DOUBLE NULL,
  `DataGewicht` DOUBLE NULL,
  `DataLicht` DOUBLE NULL,
  `DataCo2` DOUBLE NULL,
  `DataLuftfeuchtigkeit` DOUBLE NULL,
  `seriennummer_idSeriennummer` INT(11) NOT NULL,
  PRIMARY KEY (`idData`),
  INDEX `fk_data_seriennummer1_idx` (`seriennummer_idSeriennummer` ASC),
  CONSTRAINT `fk_data_seriennummer1`
    FOREIGN KEY (`seriennummer_idSeriennummer`)
    REFERENCES `projektentomophagie`.`seriennummer` (`idSeriennummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
